# Generated by Django 5.1.4 on 2024-12-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='ip',
        ),
    ]
