# Generated by Django 5.1.4 on 2024-12-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_ip_customuser_ip_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users Data'},
        ),
    ]
