# Generated by Django 5.1.4 on 2024-12-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='IP',
            field=models.GenericIPAddressField(),
        ),
    ]
