# Generated by Django 5.1.4 on 2024-12-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_customuser_last_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='submission_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
