# Generated by Django 5.1.4 on 2024-12-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_customuser_submission_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='submission_count',
        ),
    ]
