# Generated by Django 5.1.4 on 2024-12-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Users Data'},
        ),
    ]
